from datetime import datetime
from uuid import UUID

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base
from .enums import AlertType


class ComplianceAlert(Base):
    """
    A compliance deadline alert for an active worker.

    Alerts are generated by the Celery compliance-checker task that runs daily.
    Each alert type corresponds to a document or status that requires renewal.

    Lifecycle:
        created → acknowledged=False (alert raised, ops team must act)
        acknowledged=True            (ops team has seen/resolved the alert)

    The Celery task should not create duplicate alerts — check for an existing
    unacknowledged alert with the same (worker_id, alert_type) before inserting.
    """

    __tablename__ = "compliance_alerts"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("uuid_generate_v4()"),
    )
    worker_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        sa.ForeignKey("workers.id", ondelete="CASCADE"),
        nullable=False,
    )
    alert_type: Mapped[AlertType] = mapped_column(
        sa.Enum(AlertType, name="alert_type", create_type=False),
        nullable=False,
    )
    # The date by which action must be taken (expiry date of the document/permit)
    due_date: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=False
    )
    # Set to True when the ops team has acknowledged and acted on the alert
    acknowledged: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.false()
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    )
