"use client";

import { useEffect, useRef } from "react";
import Script from "next/script";

// HRappka widget language codes.
// The widget script accepts a `lang` query-param or data attribute.
const LOCALE_TO_HRAPPKA_LANG: Record<string, string> = {
  pl: "pl",
  en: "en",
  de: "de",
  nl: "nl",
  ru: "ru",
  uk: "uk",
};

type Props = {
  locale: string;
};

// The widget script URL is set via NEXT_PUBLIC_HRAPPKA_WIDGET_SCRIPT_URL in Vercel
// environment variables. It is the URL generated by HRappka under:
//   Ustawienia > Moduły > Rekrutacje > Integracja z www > (your widget)
// Example: https://app.hrappka.pl/widget/recruitment/WIDGET_ID.js
const WIDGET_SCRIPT_URL = process.env.NEXT_PUBLIC_HRAPPKA_WIDGET_SCRIPT_URL ?? "";

export function HRappkaWidget({ locale }: Props) {
  const lang = LOCALE_TO_HRAPPKA_LANG[locale] ?? "pl";
  const containerRef = useRef<HTMLDivElement>(null);

  // Re-init the widget on locale change (HRappka may expose a global reinit fn).
  useEffect(() => {
    if (!WIDGET_SCRIPT_URL) return;
    if (typeof window === "undefined") return;

    // If the widget exposes a global re-render hook, call it.
    const w = window as typeof window & { hrappkaWidget?: { setLang: (l: string) => void } };
    if (w.hrappkaWidget?.setLang) {
      w.hrappkaWidget.setLang(lang);
    }
  }, [lang]);

  if (!WIDGET_SCRIPT_URL) {
    return (
      <div className="max-w-3xl mx-auto text-center py-16 px-4 text-gray-500 text-sm">
        Widget HRappka nie jest jeszcze skonfigurowany.{" "}
        Ustaw zmienną środowiskową{" "}
        <code className="font-mono bg-gray-100 px-1 rounded">
          NEXT_PUBLIC_HRAPPKA_WIDGET_SCRIPT_URL
        </code>{" "}
        na URL widgetu wygenerowany w HRappka.
      </div>
    );
  }

  // Append ?lang= to the script URL so HRappka renders in the right language.
  // HRappka's widget script reads this param on load.
  const scriptSrc = WIDGET_SCRIPT_URL.includes("?")
    ? `${WIDGET_SCRIPT_URL}&lang=${lang}`
    : `${WIDGET_SCRIPT_URL}?lang=${lang}`;

  return (
    <div className="hrappka-widget-wrapper">
      {/* HRappka mounts its UI into this container div. */}
      <div ref={containerRef} id="hrappka-recruitment-widget" />
      <Script
        key={`hrappka-widget-${lang}`}
        src={scriptSrc}
        strategy="afterInteractive"
      />
    </div>
  );
}
